AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy ECS service components.

Parameters:
  PublicSubnetOneID:
    Type: String
    Default: subnet-0e2cc1721e990cfbc
  PublicSubnetTwoID:
    Type: String
    Default: subnet-0dd9f4df209bc1c91
  ECSSecurityGroupID:
    Type: String
    Default: sg-0e79f384f681e9d44
  TargetGroupARN:
    Type: String
    Default: arn:aws:elasticloadbalancing:ap-southeast-1:276662339380:targetgroup/ecs-in-Targe-BPUKUQPFKT0W/9f17f2ad2013b3ab

Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: "light-client-cluster"

  ECRRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "polkadot-light-client"

  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: "light-client-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: "polkadot-light-client-container"
          Image: public.ecr.aws/t2c9f5w1/polkadot-light-client:latest
          Essential: true
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: "HOSTNAME"
              Value: "localhost"
            - Name: "PORT"
              Value: "3000"

  ECSTaskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ECSTaskExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:GetRepositoryPolicy"
                  - "ecr:DescribeRepositories"
                  - "ecr:ListImages"
                  - "ecr:DescribeImages"
                  - "ecr:BatchGetImage"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  ECSService:
    Type: "AWS::ECS::Service"
    DependsOn: "ECSTaskDefinition"
    Properties:
      ServiceName: "light-client-service"
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: "FARGATE"
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnetOneID
            - !Ref PublicSubnetTwoID
          SecurityGroups:
            - !Ref ECSSecurityGroupID
          AssignPublicIp: "ENABLED"
      LoadBalancers:
        - ContainerName: "polkadot-light-client-container"
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroupARN
